# Generated by Django 5.0.6 on 2024-06-16 01:04

import django.db.models.deletion
import open_library.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('date_of_membership', models.DateTimeField(auto_now=True)),
                ('number_of_books_borrowed', models.IntegerField(default=0)),
                ('max_book_limit', models.IntegerField(default=3)),
                ('address', models.CharField(max_length=255)),
                ('is_signed_up', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='open_library.member')),
                ('biograph', models.TextField()),
            ],
            bases=('open_library.member',),
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='open_library.member')),
            ],
            bases=('open_library.member',),
        ),
        migrations.AddField(
            model_name='member',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='open_library.library'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year_published', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('B', 'BORROW'), ('NOT_AV', 'NOT_AVAILABLE')], default='B', max_length=6)),
                ('ISBN', models.CharField(default=open_library.utility.generate_isbn, max_length=13, unique=True)),
                ('date_borrowed', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to='open_library.member')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='open_library.library')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_library.author')),
            ],
        ),
    ]
